import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "ClassiMail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const CLIENT_ID =
    process.env.CLIENT_ID == undefined ? "" : process.env.CLIENT_ID;

  return (
    <html lang="en" className="">
      <AuthProvider>
        <body
          className={`${inter.className} container mx-auto relative bg-neutral-100 dark:bg-slate-900`}
        >
          <GoogleOAuthProvider clientId={CLIENT_ID}>
            {children}
          </GoogleOAuthProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
