import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ClassiMail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const CLIENT_ID =
    process.env.CLIENT_ID == undefined ? "" : process.env.CLIENT_ID;

  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto`}>
        <GoogleOAuthProvider clientId={CLIENT_ID}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
